project_id = "pxoqpyroqzsawbwajvkr"

[functions.process-trial-ended-emails]
verify_jwt = false

[functions.stripe-license-email]
verify_jwt = false

[functions.process-checkout-recovery]
verify_jwt = false

[functions.send-app-update-emails]
verify_jwt = false

[functions.send-to-mac]
verify_jwt = false

[functions.macwall-apns]
verify_jwt = false

[functions.macwall-license-verify]
verify_jwt = false

[functions.approve-community-upload]
verify_jwt = true

[functions.admin-resend-license]
verify_jwt = false
