/** Mirrors public brand strings from MacWall macOS app (`AppBrand` in Theme.swift). */

/**
 * Whop hosted checkout (same URL as `MacWallPaidCheckoutURL` in `MacWall-Branding.plist`).
 * Optional override: `NEXT_PUBLIC_MACWALL_PRO_CHECKOUT_URL` in `.env.local` for staging.
 * Completing checkout fires Whop → your Supabase `whop-license-email` webhook → license email (Resend).
 */
const proCheckoutFromEnv =
  process.env.NEXT_PUBLIC_MACWALL_PRO_CHECKOUT_URL?.trim()
export const macwallProCheckoutURL =
  proCheckoutFromEnv && proCheckoutFromEnv.length > 0
    ? proCheckoutFromEnv
    : "https://whop.com/checkout/plan_XburB7qWsnvR8"

/** Post-checkout landing page — set as Whop success redirect + Google Ads purchase conversion URL. */
export const macwallThankYouPath = "/thank-you" as const

/**
 * App icon in `public/` (512×512), generated by `npm run icons:build` from
 * Xcode `AppIcon.appiconset/1024.png` (MacWall macOS project), not from screenshots.
 */
export const macwallAppIconPath = "/macwall-app-icon.png" as const

/** Matches `scripts/build-macwall-icons.mjs` corner ratio — outer silhouette only. */
export const macwallAppIconRadiusClass = "rounded-[22.37%]" as const

export const macwall = {
  name: "MacWall",
  tagline: "4K Live Wallpapers for Mac. Pay Once, Own It.",
  website: "https://macwall.app",
  /** Community invite — matches `discordInviteURLString` in the Mac app. */
  discordInvite: "https://discord.gg/qhtYwEvHND",
  supportEmail: "support@macwall.app",
  /** Reel refund program — 50% at 2k views, 100% at 20k views. */
  reelRefundEmail: "discount@macwall.com",
  reelRefundInstagram: "@macwallapp",
  reelRefundInstagramURL: "https://www.instagram.com/macwallapp",
  reelRefundTiktok: "@macwall2",
  reelRefundTiktokURL: "https://www.tiktok.com/@macwall2",
  reelRefundHashtag: "#macwall",
  reelRefundHashtagURL: "https://www.instagram.com/explore/tags/macwall/",
  reelRefundHalfViews: 2_000,
  reelRefundFullViews: 20_000,
  legalTerms: "https://macwall.app/terms",
  legalPrivacy: "https://macwall.app/privacy",
  /** Shown at top of Terms / Privacy (update when policies change). */
  legalEffectiveDate: "May 9, 2026",
  /** ISO form for JSON-LD `dateModified` (keep in sync with `legalEffectiveDate`). */
  legalEffectiveDateIso: "2026-05-09",
  /** Same buckets as Home → Categories in the Mac app */
  categories: [
    "Nature",
    "Space",
    "Anime",
    "Cars",
    "City",
    "Video Games",
    "Sci-fi",
    "Fantasy",
    "Cats",
  ],
  pro: {
    headline: "Early Bird Offer",
    strikePrice: "$9.99",
    price: "$7.99",
    suffix: "one-time",
    socialProofMembers: "5,000",
    features: [
      "Exclusive wallpapers",
      "Lock Screen live wallpapers",
      "Unlimited playlists",
      "Future Pro features",
    ],
  },
  /** Shown in Pro discount flows (`AppBrand.proDiscountPromoCode` in Theme.swift). */
  proDiscountPromoCode: "MACWALLPRO",
  /** Personal license device limit (`AppBrand.maxLicensedMacs`). */
  maxLicensedMacs: 3,
  /** Everything included with a Pro license. */
  proIncludedFeatures: [
    "Cloud catalog: featured, newest, and popular",
    "Explore with search, filters, and community likes",
    "Save favorites and browse by category",
    "Import your own video files",
    "One player per display (hardware decode)",
    "Pause on full-screen and on battery",
    "Menu bar controls: pause, resume, stop",
  ],
} as const

export const mailtoReelRefund = `mailto:${macwall.reelRefundEmail}`
export const mailtoSupport = `mailto:${macwall.supportEmail}`

/**
 * Stable canonical path served by `/download/latest` (302 → `MACWALL_INSTALLER_REDIRECT_URL`).
 * Same pattern as `https://download.example.app/latest` → object storage URL.
 */
export const macwallInstallerLatestPath = "/download/latest" as const
