/**
 * Keyword hints for the moderation queue: names in a title that usually mean
 * third-party IP (franchises, brands, real people). A hit is a prompt to check
 * the rights declaration and source more carefully, not a finding of
 * infringement, and no hit does not mean the content is cleared.
 */
const IP_KEYWORD_GROUPS: Record<string, string[]> = {
  "Anime / manga": [
    "naruto",
    "itachi",
    "kakashi",
    "sasuke",
    "akatsuki",
    "goku",
    "dragon ball",
    "one piece",
    "luffy",
    "zoro",
    "demon slayer",
    "tanjiro",
    "nezuko",
    "jujutsu",
    "gojo",
    "sukuna",
    "nobara",
    "chainsaw man",
    "makima",
    "denji",
    "attack on titan",
    "eren",
    "levi",
    "evangelion",
    "asuka",
    "solo leveling",
    "jin-woo",
    "bleach",
    "ichigo",
    "death note",
    "hunter x hunter",
    "pokemon",
    "pikachu",
    "gengar",
    "ghibli",
    "totoro",
    "cyberpunk edgerunners",
    "lucy",
  ],
  "Comics / film / TV": [
    "marvel",
    "spider-man",
    "spiderman",
    "spider-verse",
    "miles morales",
    "venom",
    "iron man",
    "thanos",
    "avengers",
    "batman",
    "joker",
    "superman",
    "dc comics",
    "deadpool",
    "harry potter",
    "hogwarts",
    "star wars",
    "darth vader",
    "stranger things",
    "rick and morty",
    "gravity falls",
    "the simpsons",
    "breaking bad",
  ],
  Games: [
    "minecraft",
    "fortnite",
    "valorant",
    "league of legends",
    "gta",
    "vice city",
    "red dead",
    "arthur morgan",
    "elden ring",
    "zelda",
    "mario",
    "sonic",
    "halo",
    "god of war",
    "kratos",
    "ghost of",
    "cyberpunk 2077",
    "call of duty",
    "assassin",
    "the witcher",
    "need for speed",
    "marvel rivals",
  ],
  "Cars / brands": [
    "ferrari",
    "lamborghini",
    "porsche",
    "bmw",
    "mercedes",
    "mclaren",
    "bugatti",
    "audi",
    "nissan",
    "gt-r",
    "toyota",
    "supra",
    "ford mustang",
    "tesla",
    "f1",
    "formula 1",
    "formula one",
    "red bull",
    "nike",
    "adidas",
    "apple",
    "spacex",
    "amd",
    "nvidia",
    "rog",
    "bitcoin",
  ],
  "Real people / clubs": [
    "ronaldo",
    "messi",
    "neymar",
    "mbappe",
    "mbappé",
    "yamal",
    "virat",
    "kohli",
    "dhoni",
    "federer",
    "verstappen",
    "leclerc",
    "hamilton",
    "real madrid",
    "barcelona",
    "manchester united",
    "arsenal",
    "chelsea",
    "sabrina carpenter",
    "taylor swift",
  ],
}

export function ipKeywordFlags(text: string): string[] {
  const haystack = ` ${text.toLowerCase()} `
  const hits: string[] = []
  for (const [group, words] of Object.entries(IP_KEYWORD_GROUPS)) {
    const matched = words.filter((word) => {
      const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
      return new RegExp(`[^a-z0-9]${escaped}[^a-z0-9]`).test(haystack)
    })
    if (matched.length) hits.push(`${group}: ${matched.join(", ")}`)
  }
  return hits
}
